---
server:
  port: ${CONFIG_SERVER_PORT:8888}
spring:
  application:
    name: config-service
  profiles:
    active: ${CONFIG_SERVER_PROFILE:native}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_REPO}
        native:
          searchLocations: ../_local_config